
<TextIdentifier
	xmlns:cws="http://schemas.cordys.com/cws/1.0"
	type="com.cordys.translation.TextIdentifier"
	typeVersion="55890f21-u239-76j6-988a-92j7opq6ws09"
	RuntimeDocumentID="8C1645B9-0967-A1E9-B7D8-8E10DA44665F">
	<DocumentID>8C1645B9-0967-A1E9-B7D8-8E10DA44265F</DocumentID>
	<Name>8C1645B9-0967-A1E9-B7D8-8E10DA44265F</Name>
	<Description>Catch Exception</Description>
	<CreatedBy>sysadmin</CreatedBy>
	<CreationDate>2019-09-25T07:01:26.17</CreationDate>
	<Notes/>
	<DefaultText>Catch Exception</DefaultText>
	<TranslationInformation>
		<uri
			id="8C1645B9-0967-A1E9-B06A-CC7BA1252657"
		/>
	</TranslationInformation>
	<Translations>
		<uri
			id="8C1645B9-0967-A1E9-B7D8-8E10DA44A65F"
		/>
	</Translations>
</TextIdentifier>
