
<TextIdentifier
	xmlns:cws="http://schemas.cordys.com/cws/1.0"
	type="com.cordys.translation.TextIdentifier"
	typeVersion="55890f21-u239-76j6-988a-92j7opq6ws09"
	RuntimeDocumentID="50EB711A-AD5A-A1EC-B801-AFA550672B87">
	<DocumentID>50EB711A-AD5A-A1EC-B801-AFA55066EB87</DocumentID>
	<Name>50EB711A-AD5A-A1EC-B801-AFA55066EB87</Name>
	<Description>Catch Exception</Description>
	<CreatedBy>sysadmin</CreatedBy>
	<CreationDate>2022-05-30T10:54:57.099</CreationDate>
	<Notes/>
	<DefaultText>Catch Exception</DefaultText>
	<TranslationInformation>
		<uri
			id="50EB711A-AD5A-A1EC-B49C-3644C8A7EB84"
		/>
	</TranslationInformation>
	<Translations>
		<uri
			id="50EB711A-AD5A-A1EC-B801-AFA550676B87"
		/>
	</Translations>
</TextIdentifier>
